[package]
name = "loading-bay-game"
version.workspace = true
edition.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
asset-catalog.workspace = true
asset-import.workspace = true
authored-scene.workspace = true
content-store.workspace = true
core-assets.workspace = true
core-ids.workspace = true
core-math.workspace = true
core-space.workspace = true
core-time.workspace = true
core-voxel.workspace = true
engine-inspector.workspace = true
engine-spatial.workspace = true
environment-authoring.workspace = true
render-model.workspace = true
render-projection.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_path_to_error.workspace = true
tungstenite.workspace = true
entity-state.workspace = true
voxel-asset.workspace = true
voxel-annotation.workspace = true
voxel-convert.workspace = true
voxel-object-runtime.workspace = true
